/**
 * @fileoverview RisuAI Plugin API v3.0 Data Models, Runtime Contracts & Storage Schemas
 *
 * This module defines TypeScript types, interfaces, runtime contracts, storage schemas,
 * and type guards for RisuAI's internal data structures and Plugin API v3.0 specifications.
 * Based on RisuAI core architecture (`database.svelte.ts` schema and plugin sandbox).
 *
 * @see https://github.com/kwaroran/RisuAI
 * @version 3.0.0
 */

// ============================================================================
// 1. Message & Chat Data Models
// ============================================================================

/**
 * Valid role identifiers for chat messages in RisuAI.
 * - `'user'`: Message sent by the human user or active persona.
 * - `'char'`: Message generated by the AI character.
 */
export type RisuMessageRole = 'user' | 'char' | (string & {});

/**
 * Context inclusion state for an individual message:
 * - `false`: Message is included in LLM context prompt (default active state).
 * - `true`: Message is individually excluded from LLM context prompt.
 * - `'allBefore'`: All messages prior to this message (inclusive) are excluded from context.
 */
export type RisuMessageDisabled = boolean | 'allBefore';

/**
 * Single message entry within a RisuAI chat session.
 */
export interface RisuMessage {
  /** Role identifier designating the message sender ('user' | 'char') */
  role: RisuMessageRole;
  /** Raw textual content of the message including markdown, dialogue formatting, and HTML tags */
  data: string;
  /** Spoken dialogue extracted or designated for TTS (Text-to-Speech) synthesis */
  saying?: string;
  /** Unique message identifier (UUID or session-local ID) */
  chatId?: string;
  /** Creation Unix timestamp in milliseconds */
  time?: number;
  /** Speaker display name override (used in multi-character/group chats) */
  name?: string;
  /** Flag indicating whether the message originates from an auxiliary user persona */
  otherUser?: boolean;
  /** Exclusion flag for LLM prompt context construction */
  disabled?: RisuMessageDisabled;
  /** Whether this item is an author's comment/note rather than an active dialogue message */
  isComment?: boolean;
  /** Emotion asset key associated with this message turn (e.g. "happy", "angry") */
  emotion?: string;
  /** Audio asset URL or identifier associated with voice output */
  audio?: string;
  /** Extensible index signature for forward compatibility */
  [key: string]: unknown;
}

/**
 * Folder categorization for organizing character chat sessions in the sidebar UI.
 */
export interface RisuChatFolder {
  /** Unique folder identifier */
  id: string;
  /** Optional human-readable display name of the folder */
  name?: string;
  /** Optional hex or CSS color code for folder badge styling */
  color?: string;
  /** Whether the folder is collapsed in the chat selection sidebar */
  folded: boolean;
  /** Extensible index signature for forward compatibility */
  [key: string]: unknown;
}

/**
 * Individual chat conversation session with a character or group.
 */
export interface RisuChat {
  /** Ordered array of messages comprising the chat history */
  message: RisuMessage[];
  /** Scenario / author's note specific to this chat session */
  note: string;
  /** User-assigned title of the chat session */
  name: string;
  /** Unique session identifier */
  id?: string;
  /** ID of the user persona bound to this chat session */
  bindedPersona?: string;
  /** Selected first message / greeting alternative index */
  fmIndex?: number;
  /** Containing folder identifier matching `RisuChatFolder.id` */
  folderId?: string;
  /** Last activity Unix timestamp in milliseconds */
  lastDate?: number;
  /** Array of bookmarked message IDs (`chatId`) */
  bookmarks?: string[];
  /** Mapping of message `chatId` to user-defined bookmark label */
  bookmarkNames?: Record<string, string>;
  /** Chat-local lorebook entries */
  localLore?: unknown[];
  /** Stable Diffusion generation prompt metadata */
  sdData?: string;
  /** SupaMemory summary and state data */
  supaMemoryData?: string;
  /** Hypa memory V2 embedding vector data */
  hypaV2Data?: unknown;
  /** Hypa memory V3 embedding vector data */
  hypaV3Data?: unknown;
  /** Most recent summarized memory text */
  lastMemory?: string;
  /** AI-generated follow-up message suggestions */
  suggestMessages?: string[];
  /** Whether chat response is currently streaming */
  isStreaming?: boolean;
  /** Custom script runtime state */
  scriptstate?: unknown;
  /** List of enabled module IDs active in this chat */
  modules?: string[];
  /** Extensible index signature for forward compatibility */
  [key: string]: unknown;
}

// ============================================================================
// 2. Character & Group Chat Data Models
// ============================================================================

/**
 * Entity type indicating single character vs multi-character group chat.
 */
export type RisuCharacterType = 'character' | 'group' | (string & {});

/**
 * 3-tuple asset definition: `[assetId, filename, mimeType]`.
 * Used for additional assets attached to character cards and modules.
 */
export type RisuAssetTuple = [id: string, name: string, type: string];

/**
 * 2-tuple emotion portrait definition: `[emotionKey, assetId]`.
 * Used to map emotional expressions to avatar image asset IDs.
 */
export type RisuEmotionTuple = [emotion: string, assetId: string];

/**
 * RisuAI Character entity representing single character data, definitions, and chat sessions.
 * Based on RisuAI `character` interface in `database.svelte.ts`.
 */
export interface RisuCharacter {
  /** Character display name */
  name: string;
  /** Primary avatar asset identifier (e.g. "assets/..."). Note: Replaces legacy `avatar` field */
  image?: string;
  /** Unique character identifier */
  chaId: string;
  /** List of chat conversation sessions for this character */
  chats: RisuChat[];
  /** Currently active chat session index (0-indexed) */
  chatPage: number;
  /** Chat folder organization list */
  chatFolders?: RisuChatFolder[];
  /** Entity discriminator ('character' or 'group') */
  type?: RisuCharacterType;
  /** Primary greeting message */
  firstMessage?: string;
  /** List of alternative opening greetings */
  alternateGreetings?: string[];
  /** Selected alternate greeting index */
  firstMsgIndex?: number;
  /** Additional asset files attached to this character card [id, filename, mimeType] */
  additionalAssets?: RisuAssetTuple[];
  /** Emotion expression image mappings [emotionKey, assetId] */
  emotionImages?: RisuEmotionTuple[];
  /** Whether character displays in full-body/large portrait mode */
  largePortrait?: boolean;
  /** Display nickname override */
  nickname?: string;
  /** Whether the avatar icon is hidden in chat UI */
  hideChatIcon?: boolean;
  /** Character description prompt */
  description?: string;
  /** Character personality definition prompt */
  personality?: string;
  /** Scenario / situation setting prompt */
  scenario?: string;
  /** Example dialogue lines (<START>...) */
  mesExamples?: string;
  /** Creator notes and usage guidelines */
  creatorNotes?: string;
  /** Character-level system prompt override */
  systemPrompt?: string;
  /** Post-history instructions prompt */
  postHistoryInstructions?: string;
  /** Categorization tags */
  tags?: string[];
  /** Creator / author name */
  creator?: string;
  /** Character specification / version string */
  characterVersion?: string;
  /** Extensible index signature for forward compatibility */
  [key: string]: unknown;
}

/**
 * RisuAI Group Chat entity combining multiple character definitions into a shared chat room.
 */
export interface RisuGroupChat extends RisuCharacter {
  /** Entity discriminator strictly typed to 'group' */
  type: 'group';
  /** Array of participating character `chaId` identifiers */
  characters: string[];
  /** Talk frequency weighting / turn counts per character */
  characterTalks: number[];
  /** Active participating state flag per character */
  characterActive: boolean[];
}

// ============================================================================
// 3. User Persona, Modules & Database Subset Models
// ============================================================================

/**
 * User persona profile definition.
 */
export interface RisuPersona {
  /** Unique persona identifier */
  id?: string;
  /** Persona display name */
  name: string;
  /** Avatar image asset identifier (e.g. "assets/...") */
  icon: string;
  /** Persona description / system prompt text */
  personaPrompt?: string;
  /** Whether persona uses large portrait display mode */
  largePortrait?: boolean;
  /** Persona user notes */
  note?: string;
  /** Extensible index signature for forward compatibility */
  [key: string]: unknown;
}

/**
 * RisuAI Module definition for extensions, lorebooks, and regex scripts.
 */
export interface RisuModule {
  /** Unique module identifier */
  id: string;
  /** Module display name */
  name: string;
  /** Module description */
  description: string;
  /** Embedded lorebook entries */
  lorebook?: unknown[];
  /** Regex script replacements */
  regex?: unknown[];
  /** CommonJS script source code */
  cjs?: string;
  /** Trigger script definitions */
  trigger?: unknown[];
  /** Low level system access permission flag */
  lowLevelAccess?: boolean;
  /** Whether module icon is hidden in UI */
  hideIcon?: boolean;
  /** Background embedding model identifier */
  backgroundEmbedding?: string;
  /** Attached asset tuples [id, filename, mimeType] */
  assets?: RisuAssetTuple[];
  /** Module namespace string */
  namespace?: string;
  /** Custom module toggle identifier */
  customModuleToggle?: string;
  /** MCP (Model Context Protocol) tool configurations */
  mcp?: Record<string, unknown>;
  /** Extensible index signature for forward compatibility */
  [key: string]: unknown;
}

/**
 * Color scheme definition for RisuAI UI theming.
 */
export interface RisuColorScheme {
  /** Main background color */
  bgcolor: string;
  /** Dark background color variant */
  darkbg: string;
  /** Primary border color */
  borderc: string;
  /** Selection highlight color */
  selected: string;
  /** Accent red color */
  draculared: string;
  /** Primary text color */
  textcolor: string;
  /** Secondary text color */
  textcolor2: string;
  /** Dark border color variant */
  darkBorderc: string;
  /** Dark button color */
  darkbutton: string;
  /** Theme brightness type */
  type: 'light' | 'dark';
}

/**
 * Custom text theme definition for chat text formatting styles.
 */
export interface RisuCustomTextTheme {
  /** Standard body font color */
  FontColorStandard: string;
  /** Bold text font color */
  FontColorBold: string;
  /** Italic text font color */
  FontColorItalic: string;
  /** Bold-italic text font color */
  FontColorItalicBold: string;
  /** Level 1 blockquote font color */
  FontColorQuote1: string;
  /** Level 2 blockquote font color */
  FontColorQuote2: string;
}

/**
 * Known database property keys queryable via `risuai.getDatabase()`.
 */
export type RisuDatabaseKey =
  | 'characters'
  | 'personas'
  | 'selectedPersona'
  | 'userIcon'
  | 'username'
  | 'theme'
  | 'textTheme'
  | 'customCSS'
  | 'pluginCustomStorage'
  | 'modules'
  | 'enabledModules'
  | 'temperature'
  | 'maxContext'
  | 'maxResponse'
  | 'frequencyPenalty'
  | 'PresensePenalty'
  | 'colorSchemeName'
  | (string & {});

/**
 * Partial database structure accessible by plugins via `risuai.getDatabase()`.
 */
export interface RisuDatabaseSubset {
  /** List of loaded characters and group chats */
  characters?: (RisuCharacter | RisuGroupChat)[];
  /** User persona profiles */
  personas?: RisuPersona[];
  /** Active persona ID */
  selectedPersona?: string;
  /** Default user avatar asset ID */
  userIcon?: string;
  /** Default username */
  username?: string;
  /** Active UI theme name */
  theme?: string;
  /** Active text theme name */
  textTheme?: string;
  /** Global custom CSS injection */
  customCSS?: string;
  /** Plugin custom storage object */
  pluginCustomStorage?: Record<string, unknown>;
  /** Installed RisuAI modules */
  modules?: RisuModule[];
  /** Enabled module IDs */
  enabledModules?: string[];
  /** Temperature generation parameter (0-100) */
  temperature?: number;
  /** Maximum context tokens */
  maxContext?: number;
  /** Maximum response tokens */
  maxResponse?: number;
  /** Frequency penalty parameter (0-100) */
  frequencyPenalty?: number;
  /** Presence penalty parameter (0-100) */
  PresensePenalty?: number;
  /** Active color scheme name */
  colorSchemeName?: string;
  /** Extensible index signature for forward compatibility */
  [key: string]: unknown;
}

// ============================================================================
// 4. Plugin Runtime Environment & Metadata Types
// ============================================================================

/**
 * Operating platform running the RisuAI host application.
 */
export type RisuPlatform = 'web' | 'tauri' | 'electron' | 'node' | (string & {});

/**
 * Data persistence mechanism used by the host instance.
 */
export type RisuSaveMethod = 'indexeddb' | 'file' | 'memory' | (string & {});

/**
 * Host runtime environment information returned by `risuai.getRuntimeInfo()`.
 */
export interface RisuRuntimeInfo {
  /** RisuAI Plugin API version (e.g., "3.0") */
  apiVersion: string;
  /** Operating platform (e.g., "web", "tauri", "electron", "node") */
  platform: RisuPlatform;
  /** Data persistence mechanism (e.g., "indexeddb", "file", "memory") */
  saveMethod: RisuSaveMethod;
}

/**
 * Security permission scopes requestable by plugins via `risuai.requestPluginPermission()`.
 */
export type RisuPluginPermission =
  | 'mainDom'
  | 'db'
  | 'fetchLogs'
  | 'replacer'
  | 'window'
  | 'nativeFetch'
  | (string & {});

/**
 * Container display mode for plugin iframe views.
 */
export type RisuContainerMode = 'fullscreen' | (string & {});

/**
 * UI icon rendering format for plugin buttons and settings tabs.
 */
export type RisuIconType = 'html' | 'img' | 'none' | (string & {});

/**
 * Script hook execution mode.
 */
export type RisuScriptMode = 'display' | 'output' | 'input' | 'process' | (string & {});

/**
 * Replacer hook execution stage.
 */
export type RisuReplacerType = 'beforeRequest' | 'afterRequest';

/**
 * Plugin argument data types configurable in header metadata.
 */
export type RisuArgumentType = 'int' | 'string' | string[];

/**
 * Response payload returned after registering a UI part or settings entry.
 */
export interface RisuUIPartResponse {
  /** Unique identifier assigned to the registered UI element */
  id: string;
}

/**
 * Custom link metadata displayed in plugin settings UI.
 */
export interface RisuPluginCustomLink {
  /** Destination URL */
  link: string;
  /** Tooltip or hover label */
  hoverText?: string;
}

/**
 * Plugin argument metadata definition.
 */
export interface RisuPluginArgMeta {
  [key: string]: Record<string, string>;
}

/**
 * RisuAI Plugin definition schema stored in settings and manifests.
 */
export interface RisuPluginDefinition {
  /** Unique internal plugin identifier */
  name: string;
  /** Human-friendly display name shown in settings */
  displayName?: string;
  /** Plugin executable script source code */
  script: string;
  /** Argument type definitions mapped by argument key */
  arguments: Record<string, RisuArgumentType>;
  /** Current configured argument values */
  realArg: Record<string, number | string>;
  /** Target API version specification */
  version?: 1 | 2 | '2.1' | '3.0';
  /** Custom links rendered in plugin manager */
  customLink: RisuPluginCustomLink[];
  /** Argument metadata entries */
  argMeta: RisuPluginArgMeta;
  /** Semantic version string of the plugin */
  versionOfPlugin?: string;
  /** Auto-update check endpoint URL */
  updateURL?: string;
}

// ============================================================================
// 5. Plugin Interceptor & Hook Contracts (TTS, MCP, Replacer)
// ============================================================================

/**
 * Context payload passed to TTS preprocessor hooks before audio synthesis.
 */
export interface RisuBeforeTTSContext {
  /** The text about to be sent to the TTS provider */
  text: string;
  /** The active character's configured TTS provider (e.g. 'openai', 'gptsovits') */
  ttsMode: string;
  /** Stable character identifier (`character.chaId`) */
  characterId: string;
}

/**
 * Result payload returned from a TTS preprocessor hook.
 */
export interface RisuBeforeTTSResult {
  /** Transformed replacement text to synthesize */
  text?: string;
  /** If true, aborts TTS playback entirely for this message turn */
  skip?: boolean;
}

/**
 * Context payload passed to TTS postprocessor hooks with raw audio bytes.
 */
export interface RisuAfterTTSContext {
  /** Raw encoded audio buffer (MP3, WAV, WebM, etc.) */
  audio: ArrayBuffer;
  /** Audio MIME type (e.g. 'audio/mpeg', 'audio/wav') */
  mimeType: string;
  /** TTS provider identifier that generated the audio */
  ttsMode: string;
  /** Stable character identifier (`character.chaId`) */
  characterId: string;
}

/**
 * Result payload returned from a TTS postprocessor hook.
 */
export interface RisuAfterTTSResult {
  /** Replacement audio buffer to play */
  audio?: ArrayBuffer;
  /** Updated MIME type if codec was modified */
  mimeType?: string;
  /** If true, aborts playback entirely */
  skip?: boolean;
}

/**
 * Model Context Protocol (MCP) tool definition.
 */
export interface RisuMCPToolDef {
  /** Unique tool name */
  name: string;
  /** Tool functionality description */
  description: string;
  /** JSON schema defining input argument shape */
  inputSchema: Record<string, unknown>;
  /** Optional documentation or metadata annotations */
  annotations?: Record<string, unknown>;
}

/**
 * Text content chunk from an MCP tool execution response.
 */
export interface RisuMCPTextContent {
  type: 'text';
  text: string;
}

/**
 * Binary media content chunk from an MCP tool execution response.
 */
export interface RisuMCPImageAudioContent {
  type: 'image' | 'audio';
  /** Base64-encoded media data */
  data: string;
  /** MIME type string (e.g. 'image/png') */
  mimeType: string;
}

/**
 * Resource content chunk from an MCP tool execution response.
 */
export interface RisuMCPResourceContent {
  type: 'resource';
  resource: {
    uri: string;
    mimeType: string;
    text: string;
  };
}

/**
 * Content union returned by MCP tool execution handlers.
 */
export type RisuMCPToolCallContent =
  | RisuMCPTextContent
  | RisuMCPImageAudioContent
  | RisuMCPResourceContent;

/**
 * Extended options supported by `risuai.nativeFetch` for bypassing CORS.
 */
export interface RisuNativeFetchOptions extends RequestInit {
  /** Request timeout in milliseconds */
  requestTimeoutMs?: number;
}

// ============================================================================
// 6. Asynchronous Storage Schemas & Contracts
// ============================================================================

/**
 * Contract for asynchronous plugin key-value storage (`risuai.pluginStorage`).
 * Provides persistent, plugin-scoped storage backed by IndexedDB or file system.
 */
export interface RisuStorage {
  /** Retrieves a parsed value by key, returning `null` if not found */
  getItem<T = unknown>(key: string): Promise<T | null>;
  /** Serializes and stores a value under the given key */
  setItem<T = unknown>(key: string, value: T): Promise<void>;
  /** Removes a stored key-value pair */
  removeItem(key: string): Promise<void>;
  /** Clears all entries stored in this plugin's scope */
  clear(): Promise<void>;
  /** Returns the key name at the specified zero-based index */
  key(index: number): Promise<string | null>;
  /** Returns an array of all stored keys */
  keys(): Promise<string[]>;
  /** Returns the total count of stored entries */
  length(): Promise<number>;
}

/**
 * Contract for asynchronous string-only local storage (`risuai.safeLocalStorage`).
 */
export interface RisuSafeLocalStorage {
  /** Retrieves a raw string value by key, returning `null` if not found */
  getItem(key: string): Promise<string | null>;
  /** Stores a string value under the given key */
  setItem(key: string, value: string): Promise<void>;
  /** Removes a stored key-value pair */
  removeItem(key: string): Promise<void>;
  /** Clears all stored entries */
  clear(): Promise<void>;
  /** Returns the key name at the specified index */
  key(index: number): Promise<string | null>;
  /** Returns the total count of stored entries */
  length(): Promise<number>;
}

/**
 * Contract for local device plugin storage (`risuai.getLocalPluginStorage()`).
 */
export interface RisuLocalPluginStorage {
  /** Retrieves a value by key */
  getItem<T = unknown>(key: string): Promise<T | null>;
  /** Stores a value under the given key */
  setItem<T = unknown>(key: string, value: T): Promise<void>;
  /** Removes a stored key-value pair */
  removeItem(key: string): Promise<void>;
  /** Clears all stored entries */
  clear(): Promise<void>;
  /** Returns an array of all stored keys */
  keys(): Promise<string[]>;
}

// ============================================================================
// 7. Global Plugin API Contract (Risuai / risuai)
// ============================================================================

/**
 * Complete contract for the RisuAI Plugin API v3.0 global object (`risuai` / `Risuai`).
 * All methods operate asynchronously over `postMessage` RPC.
 */
export interface RisuaiPluginAPIContract {
  /** API version string (e.g. "3.0") */
  apiVersion: string;
  /** Array of compatible API versions */
  apiVersionCompatibleWith: string[];

  // --- Logging & UI Management ---
  /** Logs a message prefixed with plugin identity */
  log(message: string): Promise<void>;
  /** Displays the plugin's iframe container UI */
  showContainer(mode: RisuContainerMode): Promise<void>;
  /** Hides the plugin's iframe container UI */
  hideContainer(): Promise<void>;

  // --- DOM & Observation ---
  /** Gets the SafeDocument wrapper for the main host window (requires 'mainDom' permission) */
  getRootDocument(): Promise<unknown>;
  /** Creates a safe mutation observer for DOM tracking */
  createMutationObserver(callback: (mutations: unknown) => void): Promise<unknown>;
  /** Unwraps a SafeClassArray or array-like proxy to a native JavaScript Array */
  unwarpSafeArray<T = unknown>(arr: unknown): Promise<T[]>;

  // --- Character & Chat Data Access ---
  /** Retrieves the currently active character object */
  getCharacter(): Promise<RisuCharacter | null>;
  /** Updates the currently active character object */
  setCharacter(character: RisuCharacter | unknown): Promise<void>;
  /** @deprecated Use `getCharacter()` instead */
  getChar(): Promise<unknown>;
  /** @deprecated Use `setCharacter()` instead */
  setChar(character: unknown): Promise<void>;
  /** Retrieves a character by zero-based database index */
  getCharacterFromIndex(index: number): Promise<RisuCharacter | null>;
  /** Saves a character at the specified database index */
  setCharacterToIndex(index: number, character: RisuCharacter | unknown): Promise<void>;
  /** Retrieves a specific chat session for a character */
  getChatFromIndex(characterIndex: number, chatIndex: number): Promise<RisuChat | null>;
  /** Saves a specific chat session for a character */
  setChatToIndex(characterIndex: number, chatIndex: number, chat: RisuChat | unknown): Promise<void>;
  /** Returns the index of the currently active character */
  getCurrentCharacterIndex(): Promise<number>;
  /** Returns the index of the currently active chat session */
  getCurrentChatIndex(): Promise<number>;
  /** Retrieves lorebook entries active in the current session */
  getCurrentLorebookEntries(): Promise<unknown[]>;

  // --- Database Access ---
  /** Queries database properties by key names or `'all'` */
  getDatabase(includeOnly?: RisuDatabaseKey[] | 'all'): Promise<RisuDatabaseSubset | null>;
  /** Lightweight database update */
  setDatabaseLite(db: Partial<RisuDatabaseSubset>): Promise<void>;
  /** Complete database update */
  setDatabase(db: Partial<RisuDatabaseSubset>): Promise<void>;

  // --- Storage Instances ---
  /** Asynchronous key-value plugin storage */
  pluginStorage: RisuStorage;
  /** String-only safe local storage */
  safeLocalStorage: RisuSafeLocalStorage;
  /** Retrieves local device plugin storage instance */
  getLocalPluginStorage(): Promise<RisuLocalPluginStorage>;

  // --- Arguments & Settings ---
  /** Gets configured value for a declared plugin argument */
  getArgument<T = string | number | undefined>(key: string): Promise<T>;
  /** Sets value for a declared plugin argument */
  setArgument(key: string, value: string | number): Promise<void>;
  /** @deprecated Synchronous argument getter (use `getArgument`) */
  getArg(key: string): unknown;
  /** @deprecated Synchronous argument setter (use `setArgument`) */
  setArg(key: string, value: string | number): void;

  // --- UI Registration ---
  /** Registers a settings menu item with custom click handler */
  registerSetting(
    name: string,
    callback: () => void | Promise<void>,
    icon?: string,
    iconType?: RisuIconType,
    id?: string
  ): Promise<RisuUIPartResponse>;
  /** Registers a button in RisuAI toolbars */
  registerButton(
    arg: Record<string, unknown>,
    callback: () => void | Promise<void>
  ): Promise<RisuUIPartResponse>;
  /** Unregisters a previously registered UI part by ID */
  unregisterUIPart(id: string): Promise<void>;

  // --- Theming & Styling ---
  /** Switches active color scheme by preset name */
  changeColorScheme(name: string): Promise<void>;
  /** Applies custom color scheme */
  setColorScheme(scheme: Partial<RisuColorScheme>): Promise<void>;
  /** Gets currently active color scheme */
  getColorScheme(): Promise<{ name: string; scheme: RisuColorScheme }>;
  /** Switches active text theme */
  changeTextTheme(name: string): Promise<void>;
  /** Applies custom text styling theme */
  setCustomTextTheme(theme: Partial<RisuCustomTextTheme>): Promise<void>;
  /** Gets currently active text theme */
  getTextTheme(): Promise<{ name: string; customTheme: RisuCustomTextTheme }>;

  // --- Network & Native APIs ---
  /** Executes CORS-bypassing HTTP request using native host environment */
  nativeFetch(url: string, options?: RisuNativeFetchOptions): Promise<Response>;
  /** Saves secret header configuration */
  saveSecretHeader(key: string, prefix: string, value: string | string[]): Promise<void>;

  // --- Security & Permissions ---
  /** Requests user permission for a sensitive operation scope */
  requestPluginPermission(permission: RisuPluginPermission): Promise<boolean>;

  // --- Assets & Image Decoding ---
  /** Reads raw binary bytes for an asset identifier (e.g. "assets/...") */
  readImage(assetId: string): Promise<Uint8Array | ArrayBuffer>;
  /** Reads raw asset data */
  readAsset?(assetId: string): Promise<Uint8Array | ArrayBuffer>;
  /** Saves raw binary asset data, returning new asset identifier */
  saveAsset?(data: Uint8Array | ArrayBuffer, filename?: string): Promise<string>;

  // --- Interceptors & Lifecycle ---
  /** Registers a replacer hook for prompt/response manipulation */
  registerReplacer?(
    type: RisuReplacerType,
    handler: (data: unknown) => unknown | Promise<unknown>
  ): Promise<void>;
  /** Registers a TTS preprocessor hook */
  addTTSPreprocessor?(
    fn: (ctx: RisuBeforeTTSContext) => RisuBeforeTTSResult | Promise<RisuBeforeTTSResult>
  ): Promise<void>;
  /** Registers a TTS postprocessor hook */
  addTTSPostprocessor?(
    fn: (ctx: RisuAfterTTSContext) => RisuAfterTTSResult | Promise<RisuAfterTTSResult>
  ): Promise<void>;
  /** Registers plugin cleanup handler fired when plugin is disabled or reloaded */
  onUnload(callback: () => void): void;
  /** Host runtime environment info query */
  getRuntimeInfo?(): Promise<RisuRuntimeInfo>;
}

// ============================================================================
// 8. Type Guards & Runtime Validators
// ============================================================================

/**
 * Type guard to check whether a RisuCharacter entity is a multi-character group chat.
 *
 * @param character - Character object to inspect
 * @returns `true` if the character is a valid RisuGroupChat
 *
 * @example
 * ```typescript
 * const char = await risuai.getCharacter();
 * if (isRisuGroupChat(char)) {
 *   console.log('Group participants:', char.characters);
 * }
 * ```
 */
export function isRisuGroupChat(
  character: RisuCharacter | null | undefined
): character is RisuGroupChat {
  return character != null && character.type === 'group';
}

/**
 * Type guard to check whether an unknown entity satisfies the RisuCharacter contract.
 *
 * @param value - Value to inspect
 * @returns `true` if the value has valid character properties
 */
export function isRisuCharacter(value: unknown): value is RisuCharacter {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return (
    typeof candidate.name === 'string' &&
    typeof candidate.chaId === 'string' &&
    Array.isArray(candidate.chats)
  );
}

/**
 * Type guard to check whether an unknown object satisfies the basic RisuMessage contract.
 *
 * @param value - Value to inspect
 * @returns `true` if the value is a valid RisuMessage
 *
 * @example
 * ```typescript
 * if (isRisuMessage(item)) {
 *   console.log(item.role, item.data);
 * }
 * ```
 */
export function isRisuMessage(value: unknown): value is RisuMessage {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return (
    (candidate.role === 'user' || candidate.role === 'char') &&
    typeof candidate.data === 'string'
  );
}

/**
 * Type guard to check whether an unknown object satisfies the basic RisuChat contract.
 *
 * @param value - Value to inspect
 * @returns `true` if the value is a valid RisuChat
 *
 * @example
 * ```typescript
 * const chat = await risuai.getChatFromIndex(0, 0);
 * if (isRisuChat(chat)) {
 *   console.log(`Chat ${chat.name} has ${chat.message.length} messages`);
 * }
 * ```
 */
export function isRisuChat(value: unknown): value is RisuChat {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return Array.isArray(candidate.message) && typeof candidate.name === 'string';
}

/**
 * Type guard to check whether an unknown object satisfies the RisuPersona contract.
 *
 * @param value - Value to inspect
 * @returns `true` if the value is a valid RisuPersona
 */
export function isRisuPersona(value: unknown): value is RisuPersona {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return typeof candidate.name === 'string' && typeof candidate.icon === 'string';
}

/**
 * Type guard to check whether an unknown object satisfies the RisuChatFolder contract.
 *
 * @param value - Value to inspect
 * @returns `true` if the value is a valid RisuChatFolder
 */
export function isRisuChatFolder(value: unknown): value is RisuChatFolder {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return typeof candidate.id === 'string' && typeof candidate.folded === 'boolean';
}